- src/backend/renderer.js
- src/utils.js
Before:
```js
utfDecodeString(utfEncodeString("脳みそ爆発🤯"))
// => "3]z>/"
```
After:
```js
utfDecodeString(utfEncodeString("脳みそ爆発🤯"))
// => "脳みそ爆発🤯"
```
> Fix encoding of Unicode keys greater than U+00FF

- shells/browser/chrome/manifest.json
- shells/browser/firefox/manifest.json
- shells/browser/shared/src/GlobalHook.js
- shells/browser/shared/src/main.js
- shells/browser/shared/src/renderer.js
- shells/browser/shared/webpack.config.js
- src/backend/agent.js
- src/backend/index.js
- src/backend/renderer.js
- src/backend/types.js
- src/constants.js
- src/devtools/store.js
- src/devtools/views/Profiler/CommitTreeBuilder.js
- src/devtools/views/Profiler/FlamegraphChartBuilder.js
- src/devtools/views/Profiler/ProfilerContext.js
- src/devtools/views/Profiler/RankedChartBuilder.js
- src/devtools/views/Settings/SettingsContext.js
- src/hook.js
Earlier this week I started work on the "reload and profile" feature. I got it working for e.g. Code Sandbox, but not for e.g. [react-window.now.sh](https://react-window.now.sh), because the renderer interface, (the thing that walks the fiber tree and stores render durations), was not getting injected in time to catch the first couple of commits.
Getting that to work has proven to be pretty difficult because it's quite tricky to _synchronously_ inject code into the page context from an extension's content script. After a _lot_ of trial and error, I came up with a hacky potential solution that I've posted here for discussion purposes.
I'm not satisfied with this approach, as sync XHR is frowned upon and [may be deprecated in the future](https://developer.mozilla.org/en-US/docs/Web/API/XMLHt …
> Eagerly inject renderer (before document) to support reload-and-profile

- src/devtools/views/Elements/SelectedElement.js
Maybe we could do it with Suspense but I couldn't quite figure out the right way to do it yet.
This avoids the flashing "Loading..." when you switch between items fast. (Instead, it opts for a temporary inconsistency between props and the title pane.)
> Avoid flashing "Loading..." in right pane

- src/devtools/views/utils.js
This was bugging me for a while. Makes it consistent with what we do in docs and what Prettier does.
> Add a space in <Foo />

- src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/26.
I noticed search often selects a random item.
But looking closer, it was because of a partial match:
This changes the algorithm to also change the selection if you continue typing in the search field. I think this feels better. It also matches what Chrome does in text search more closely. (Although not quite — but implementing 1:1 mapping seems like too much complexity right now.)
> Move selection when typing in search field

- src/devtools/views/Components/SelectedElement.js
We could get it "by default" by using real buttons but this also works.
It's one of the most useful navigations so seems important to get it right.
> Make owner stack reachable by keyboard

- src/devtools/views/Components/Tree.js
Related to https://github.com/bvaughn/react-devtools-experimental/issues/52.
This makes the tree focusable, and handles focus by selecting the first item if none are already selected.
Once you're inside the tree, the regular keyboard shortcuts take over.
I probably missed something but happy to work more on it if you can help me find the broken cases!
> Make tree reachable by focus

- src/backend/agent.js
I noticed that in some places on FB, "selecting" an element inside a context menu will dismiss the menu. While we stop `click` and `mousedown` propagation, we didn't stop `mouseup`. Our handlers listen to it.
This makes clicking the page to choose a DOM element a bit less likely to blow away the thing you're trying to inspect — by preventing `mouseup` propagation too until your click is done.
> Stop mouseup propagation while inspecting

- src/devtools/views/Components/SelectedElement.css
Not sure if you intentionally made it smaller or it was accidental.
With Comfortable layout, they're currently 11px — which IMO is a bit too small, at least for Comfortable. This adds the closest constant I found. I don't mind them being a bit smaller than that, but IMO they're way too small right now, at least for a Comfortable mode, to the point of being hard to read.
Thanks for considering.
> Bump font size of owner stack items

- shells/dev/app/InspectableElements/CustomHooks.js
- shells/dev/app/InspectableElements/NestedProps.js
- src/devtools/views/Components/HooksTree.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/42.
This happened because the code didn't handle the dehydrated case, and the hydration level constant is set at `6`. (Which is a few levels of custom Hooks + a few levels of `subHooks` arrays.)
The fix includes a few stress tests. The nested deep Hook one used to crash, but doesn't anymore.
It's not ideal that we don't let you inspect deeper. But this can be fixed later with a UI that loads them on demand. I added todos for that.
> Don't crash for deeply nested Hooks

- src/devtools/views/Components/SearchInput.js
- src/devtools/views/utils.js
This makes searching a bit more robust.
Previously, `item` would match both `*Item*`, `List*Item*`, and `Iniv*iteM*om`.
I've changed regex to only consider a match if the first query letter is either at the beginning of the component name (such as the case with `Item`), or if it is at the word boundary (like in `ListItem`). Matches in the middle of the name where the first letter appears as lowercase are ignored.
This prevents matching `c` to `InteractionTracking`, for example:
See comments. To make this work, I had to make the regex case-sensitive. Instead, I expand the casings directly when building regex, and add a special case for the first letter.
`Listitem` would still match `ListItem`. Only the first letter in the target text is treated contextually.
> Match search at word boundaries

- src/backend/agent.js
- src/backend/renderer.js
- src/devtools/store.js
- src/devtools/views/Profiler/CommitTreeBuilder.js
I understand the convenience but without a Babel plugin it seems a bit too easy to accidentally cause extra work. Such as the `children.join(',')` we're doing on every reorder — afaik, in production too.
This is a bit noisy but seems easy enough to follow and avoids that. I added everywhere for consistency.
> Explicitly guard debug calls

- src/devtools/views/Components/TreeContext.js
This fixes the "disappearing selection" problem you found in https://github.com/bvaughn/react-devtools-experimental/pull/61#discussion_r272360830.
I introduced it in https://github.com/bvaughn/react-devtools-experimental/pull/62. The mistake is that moving from `''` to `''` in search field shouldn't reset. Only _increasing_ the search field should.
> Don't move selection unless search text increased length

- shells/dev/app/index.js
- src/backend/agent.js
- src/backend/renderer.js
- src/backend/types.js
- src/devtools/views/Components/SelectedElement.js
- src/devtools/views/Components/types.js
Supersedes https://github.com/bvaughn/react-devtools-experimental/pull/36.
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/60.
This is MVP support for toggling Suspense from the Components pane. We plan a separate tab in https://github.com/bvaughn/react-devtools-experimental/issues/43 but we'd want a way to quickly debug it anyway so seems like this is a good first step.
Currently, Suspense shows Fiber internal state in the "state" section of the inspector (when Suspended), and nothing if unsuspended. This PR changes so that we show the current Suspense state:
This works with older versions of React.
The inspected value turns into a checkbox if:
* You're using a version of React that includes https://github.com/facebook/react/pull/15232, **AND**
- The component is not …
> Allow to toggle Suspense in Components pane

- shells/dev/app/Toggle/index.js
- shells/dev/app/index.js
- src/backend/renderer.js
- src/devtools/store.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/6.
This used to happen because when converting a loop version to the recursive version of `mountFiber`, we always went into `fiber.sibling`. But we should have only done that for the inner iterations — not the topmost one.
Adds a test that demonstrates the issue on master.
> Fix double-adding fibers when traversing

- src/devtools/views/Toggle.js
The prop was previously ignored. Now the title shows up.
> Pass Toggle label through

- src/devtools/views/Components/Tree.css
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/80.
I figured this ring isn't really that useful because the first time you Tab into the tree, the first item gets selected. So you know it received focus. Chrome tree view doesn't have a focus ring either.
In the future, we might want to only enable tree arrow key navigation when the tree if focused. For example, that would allow us to repurpose up/down for owner stack navigation when owner stack is focused. If we were to do that, we could mark "focused" state of the tree with the default selection color, and "unfocused" state with a grey-ish color, similar to how Chrome Elements tab does. Even in that case, we wouldn't need a ring. But that's a future nice-to-have.
> Remove tree focus ring

- .flowconfig
- .gitignore
- src/backend/views/Overlay.js
- src/devtools/views/ButtonIcon.js
- src/devtools/views/Components/OwnersStack.css
- src/devtools/views/Components/OwnersStack.js
- src/utils.js
**Description**:
We've previously had the issue when we have a large tree that the owner stack was overflowing and a horizontal scroll was appearing.
This PR addresses this issue and adds a new look and feel to the OwnerStack component.
Now when we have a large tree a button (":") will appear next to the close ("X") button. 
Upon clicking it we expand a dropdown view of the owner stack. 
Note: We still show the current selected element in the OwnerStack bar.
**What's changed**:
- Extracted the `getElementDimensions` function to the `utils.js` file in order to be used throughout the codebase.
- Added new ButtonIcon type and SVG - `colon`
- Created new sub components that will be only used in the OwnerStack component - ElementsBar, ElementsDropdown
**Screenshots**:
Dark theme:
Light theme: …
> Owner stack enhancement

- src/devtools/views/Components/Tree.js
While this is subjective and depends on the laptop etc, I find this a bit less janky on fast scrolling. Rendering rows should be pretty cheap regardless (since we don't put much there) and I don't see regressions on large trees. WDYT?
> Bump overscan to 3

- src/devtools/views/Components/TreeContext.js
The owner mode is very cool but I barely use it because exiting it loses the context of where I was. This fixes it so that the last selected node stays selected when you exit the owner stack mode.
> Preserve selection on exiting owner mode

- src/devtools/views/Components/SelectedElement.js
I think most people don't know what an "owner" is. Additionally, "stack" has unnecessary computer science connotations. Admittedly, there's a notion of "call stack" but especially beginners don't necessarily know that this is how you call the thing that you get after the error.
This wording seems a bit friendlier to me, and more immediately useful:
> Rename "owner stack" label to "rendered by"

- shells/browser/shared/src/main.js
- src/devtools/views/DevTools.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/48.
At first I considered only preserving the scroll state. However on a second thought I realized I'd prefer the tree to stay there. For example if I'm in a middle of inspecting some component's props and then jump to Profiler and back, I don't want my right pane scroll to reset either. As we add more interactivity to the right pane (e.g. expanding props / nested Hooks deeper), this problem will keep coming up.
So I just keep all tabs mounted once they are. I use the `hidden` prop which in Concurrent Mode should make inactive tab updates low pri. Seems like it doesn't break anything, but we can also switch to `display: none` if it ends up being a problem.
> Preserve state when switching tabs

- src/devtools/views/Components/Element.js
- src/devtools/views/Components/Tree.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/67.
I'm not *super* happy with the fix because instead of overfiring, it will cause the autoscroll to underfire in some edge cases. (Such as searching for an item, scrolling away from it, and then searching for it again.) However that seems like a better tradeoff to me in the meantime than random jumps when scrolling.
We can't truly infer whether to auto-scroll or not from which virtual items are materialized, as we see from https://github.com/bvaughn/react-devtools-experimental/issues/67#issuecomment-480067969.
Another fix might be to set some flag [here](https://github.com/bvaughn/react-devtools-experimental/blob/a9c20f0b36366de81ab235cd8b3bd73fe454e513/src/devtools/views/Components/Tree.js#L44) and then reset it in the …
> Fix spurious autoscroll

- src/backend/agent.js
- src/backend/views/Highlighter.js
- src/devtools/views/Components/Element.js
- src/devtools/views/Components/SelectedElement.js
- src/devtools/views/Components/Tree.js
I know you've considered and rejected this idea before, but I'm sending in case you might reconsider.
I've been watching @threepointone struggle to use new DevTools today. Initially, he couldn't find either the "inspect from DOM" button nor the "show in DOM" button because both are small icons that are easy to miss. He was sure neither of those are implemented yet.
Even when I pointed out the toolbar buttons, he was frustrated because every time he navigated in the tree, he had to press a button to see where he was. This made navigation itself difficult because *hovering nodes to see which one he wants to select* is part of his process.
This PR is a proposal to add behavior similar to what Chrome does in Elements tab, as well as what the old DevTools did:
1. When hovering a row, we …
> Select DOM nodes on hover

- src/backend/agent.js
- src/backend/renderer.js
- src/backend/types.js
- src/devtools/views/ButtonIcon.js
- src/devtools/views/Components/SelectedElement.js
- src/devtools/views/Components/types.js
This adds a way to dump props/state into the console for further inspection. This is to make it easier to get data "out" of DevTools — e.g. to debug a deep object, trigger a callback manually, etc.
There is `$r`, of course, but I also want to have something in the UI that's more explicit.
I built this behavior into the "view in DOM" button but we could have a separate one. I figured it doesn't hurt to unify them (especially if https://github.com/bvaughn/react-devtools-experimental/pull/92 "takes over" most use cases for regular selection) but maybe my intuition is wrong.
This PR is mostly to start the conversation. Maybe this is not very useful.
> Add a way to get props/state into console

- shells/browser/shared/src/main.js
- src/backend/agent.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/59.
This implements two-way syncing between the DevTools Elements tab and the React Components tab.
I think in most cases this is what you want. Especially now that we don't show the host nodes, and so you often need to switch to Elements to play with them.
I'm not sure if there are any cases where the two-way binding gets in the way. Maybe we could offer an option to disable it as an escape hatch. Or maybe there's some smarter heuristic we could use.
> Sync DevTools Elements and Components tabs

- src/backend/views/Overlay.js
If click-to-inspect then hover an element in just the right place, it flickers between two elements because this "tip" element catches the hover. This should fix it.
> pointer-events: none to fix flicker on Overlay "tip"

- shells/browser/shared/src/main.js
- src/backend/agent.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/102 by making syncing one-way.
I'll talk to DevTools folks in case there's some way to restore the two-way binding later. Ideally I want a version of `inspect(foo)` that doesn't force a tab switch. Maybe they'll add it in the future.
The upside is apparently there's `chrome.devtools.panels.elements.onSelectionChanged` API that makes the other half easier. So I switched to that here too.
> Make DOM selection binding one-way

- .eslintignore
- .prettierignore
- package.json
- src/devtools/views/Components/OwnersStack.css
- src/devtools/views/Components/OwnersStack.js
- src/devtools/views/Components/Tree.js
- src/devtools/views/DevTools.js
- vendor/@reach/portal/.eslintignore
- vendor/@reach/portal/es/index.js
- vendor/@reach/portal/examples/basic.example.js
- vendor/@reach/portal/index.js
- vendor/@reach/portal/package.json
- vendor/@reach/portal/src/index.js
- yarn.lock
I find myself implementing arrow key navigation in several places. It would be nice to use a reusable controller for this, and the [Reach UI `MenuButton`](https://ui.reach.tech/menu-button/) looks pretty promising for this.
Couple of blockers:
> Use @reach MenuButton for owner stack menu [WIP]

- src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/100.
This becomes more important in light of merging https://github.com/bvaughn/react-devtools-experimental/pull/99 which might cause selection elsewhere in the tree. You want to be able to get back to your search results.
> Pressing next forces search to select

- shells/dev/index.html
Kinda hacky but this makes testing in browser shell easier because you don't see the overlay all the time.
> Put DevTools in dev shell above the inspector

- package.json
- src/devtools/store.js
- src/devtools/views/ButtonIcon.js
- src/devtools/views/Components/Element.css
- src/devtools/views/Components/Element.js
- src/devtools/views/Components/Tree.js
- src/devtools/views/Components/TreeContext.js
- src/devtools/views/Components/types.js
- src/devtools/views/Profiler/ProfilerContext.js
- yarn.lock
Resolves #105 (I think?)
Checklist:
> Add collapse/toggle UI to Tree

- src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/119.
This adds an `indexOf` lookup per commit. I think that's fine.
> Update selected index after mutation

- src/devtools/views/Components/Tree.js
It was missing on the "left" button.
I also moved them all to the beginning of switch cases to make them easier to spot.
> Prevent default on all key navigations

- src/backend/agent.js
- src/devtools/views/Components/InspectHostNodesToggle.js
- src/devtools/views/Components/Tree.js
Addresses part of https://github.com/bvaughn/react-devtools-experimental/issues/121.
This matches Chrome behavior.
> Picking a DOM node focuses the tree

- src/devtools/views/Components/KeyValue.css
- src/devtools/views/Components/KeyValue.js
I've got it working, but the arrow is kinda small on comfortable mode, maybe I shouldn't be using the `ButtonIcon` here?
This is comfortable mode:
> Add collapsible icon for object and array types

- src/devtools/views/Components/Element.css
- src/devtools/views/Components/Element.js
- src/devtools/views/Components/Tree.js
This cleans up the selection/hover behavior when using the keyboard.
Two main changes:
* Hover while we're using the keyboard navigation is hidden. It reappears on mousemove.
* When we're using the keyboard, the DOM selection follows the selected item.
This matches Chrome behavior. (Except that Chrome also keeps last hovered item *always* visible but doesn't update it during keyboard nav — which I think is actually worse than what this PR does.)
> Ignore hover when navigating with keyboard

- src/devtools/views/Profiler/SidebarSelectedFiberInfo.css
You couldn't scroll when the fiber commits exceeded the amount it could fit on the panel.
> Fix fiber info sidepanel not scrollable

- src/devtools/views/Components/Element.js
- src/devtools/views/Components/HooksTree.js
- src/devtools/views/Components/KeyValue.js
- Clicking expand/collapse arrow no longer selects the node. This matches Chrome behavior and ensures you can hide components with annoyingly jumpy children if you want without losing where you were in the tree.
- Also fixes https://github.com/bvaughn/react-devtools-experimental/issues/144 — a single click now expands the object properties, similar to how you normally inspect objects in the console.
> Polish some mouse interactions

- src/devtools/views/Components/TreeContext.js
When I exit the search mode, this keeps the last selected item. There's no use resetting it — and usually I want to continue from that point on.
Similarly, if the search no longer matches, this keeps the last selected item. I don't think resetting it does any good. On the opposite, it often leads to me pressing "down" and accidentally ending up on the very top of the tree.
> Don't reset selected item on search mismatch or exit

- shells/browser/shared/src/main.js
- src/backend/agent.js
- src/devtools/views/Components/SelectedElement.js
- src/devtools/views/Components/Tree.js
I haven't found much use for "view in DOM" since now we highlight on hover and keyboard navigation. However, I *do* often wish to switch to the corresponding DOM node when debugging styles and layout. Unfortunately, we don't have a two-way binding yet.
Let's solve these problems together. I'm making the "view in DOM" button open up the Elements tab *in addition* to highlighting the DOM node. This makes it more useful and fills in the missing functionality.
> View DOM button opens Elements tab

- src/devtools/views/Components/Element.css
- src/devtools/views/Components/Element.js
This has been bugging me for the last two weeks. I thought there's no good fix but this one works.
This also fixes https://github.com/bvaughn/react-devtools-experimental/issues/142. You can try it by inspecting FB trees with "find by DOM node". Previously, it would occasionally fail to fully display the whole component name. Now it always does.
> Consistently scroll component name into view

- src/__tests__/__snapshots__/store-test.js.snap
- src/__tests__/store-test.js
This adds a stress-test for the tree traversal logic. In particular, it stresses correct handling for mounting, updating, unmounting, and re-ordering elements.
There are only two snapshots for two "ideal" states. The rest of the test is taking different alternative trees which are known to produce the same DOM output, and verifying that the DevTools output also matches these known snapshots.
For each alternative tree, we test that:
* Mounting it produces the desired result
* Updating from previous tree to it _also_ produces the desired result, both in Sync and Concurrent Modes
See inline comments for more details.
It's nice to know that this passes.
> Add a stress test for tree traversal

- src/__tests__/__snapshots__/store-test.js.snap
- src/__tests__/setupTests.js
- src/__tests__/store-test.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/111. This is not a fuzzer but it's close enough and might be sufficient.
Parts of this test are commented out. As far as I can tell, the test itself is fine, but those parts don't pass due to actual bugs in the Suspense logic discovered by the test. I'll be looking into fixing them tomorrow. That doesn't block merging this though.
Follow-ups:
* Fix Suspense logic
* Test Concurrent Mode
* Test setStates inside Suspense
> Add Suspense stress test

- src/devtools/views/Settings/SettingsContext.js
- src/devtools/views/root.css
* Darkened component name color slightly
* Removed anti-aliasing
* No changes
> Improve contrast for light mode

- src/devtools/views/TabBar.js
Selecting the tab when the mouse is pressed rather than only when it is
released makes tab switching feel faster and also matches how the Chrome dev
tools behave.
The previous tab selection handler which listens for the radio button's
selection has been kept for the benefit of interaction methods which
don't trigger the mousedown handler.
> Select tab when the mouse is pressed

- src/backend/renderer.js
- src/devtools/store.js
I just spent about an hour chasing bug that was caused by wrong deletion order (the bug was in some new code, not in master).
I was misled by the comment which claims deletions are reported by React in the child-first order — whereas the opposite is true. I've fixed the comment and added an assertion that ensures this is actually the case.
> Assert removal happens in the right order

- src/__tests__/setupTests.js
React catches errors in DevTools renderer hooks. However, this means they don't fail tests.
Now they do.
> Fail tests on errors in renderer

- src/backend/renderer.js
- src/devtools/store.js
- Asserts the node count is the same between reorders
- Asserts we remove children first
- Removes the ID logging which creates a DEV-only side effect
> Harden assertions

- src/backend/agent.js
This ensures it doesn't get stuck if you Cmd+Shift+I out of DevTools. Also ensures they don't "stack up" when you launch a new DevTools window after that.
> Clear DOM overlay on shutdown

- src/backend/renderer.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/197.
This fix is not ideal. In particular, it makes dehydrated Suspense nodes appear *hidden* rather than empty. Conceptually, they're showing a server-rendered fallback, but we don't have React tree for it yet. Maybe it would be nice to show `<Suspense>` in the tree for them, but currently it's too broken so I opted to completely hide them until their hydration instead.
The reason we need this is because dehydrated Suspense nodes have funky behavior like [this](https://github.com/facebook/react/blob/d584fcdc6e10b9f4d4e9eec775731e7ffc0fb501/packages/react-reconciler/src/ReactFiberBeginWork.js#L1695-L1721) which I think violates some assumptions made by DevTools (e.g. we don't expect a Fiber to pretend it's a completely …
> Filter out dehydrated Suspense nodes

- src/backend/agent.js
The first few moments are usually spent lifting the cursor from the button to the actual place you wanna select. Since the highlighting in the browser is instantaneous anyway and will grab our attention, there's no need to immediately reflect the leading edge in the item selection. We will likely hover over the wrong thing at first. This helps avoid unintentionally expanding trees in more cases.
> Ignore leading edge of find-by-DOM throttle

- src/backend/renderer.js
There is a simpler (and likely more efficient) way to check if a Fiber has really been unmounted — its `.return` pointer would be nulled out. I was feeling uneasy due to that `WeakSet` because I'm worried putting Fibers into weak sets can mess with VM optimizations. Such as if they turn it into an expando internally. This avoids it.
Curiously, technically even the `.return` check isn't necessary here anymore. If the Fiber is deleted, it wouldn't be in the map — and so `recordUnmount` would have bailed out by now because of its inner check. The only reason this didn't work before was because in `__DEV__` we used to call `getFiberID` for them in `debug()` calls, making those Fibers go into the map. However, even though this is fixed, I don't want to rely on this, and would prefer those …
> Replace WeakSet with return pointer check

- src/devtools/store.js
- src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/189.
If we've selected an ID which is inside a collapsed subtree, its index can't be valid. We can't scroll to it. However, we don't want to "forget" the selection either.
Instead, we'll temporarily forget the index (but remember the ID) just before we exit the reducer. When the store is reconciled with selection in the layout effect, the index will be automatically recalculate. That, in turn, will trigger the scroll effect to the right index.
> Fix scrolling to selected row in collapsed mode

- src/devtools/store.js
- src/devtools/views/Components/TreeContext.js
If selected node gets unmounted, currently we reset the selection. This is somewhat disruptive because the next time you press "down" you'll jump to the top of the tree. It can be disorienting.
This fix adjusts selection to go the closest parent element that wasn't deleted in this batch. To make it work, I made `removedIDs` a Map of `removed ID -> parent ID`. We can't query the store about removed nodes by the time we receive an event, so this mapping helps us figure out which node to select instead.
I also changed `addedIDs` to be a regular array since I don't see what making it a typed array brings here. It isn't being transferred anywhere as far as I can tell, and we still used to create an array anyway. Might as well use that one.
> Select parent node if selection is removed

- src/backend/renderer.js
This makes the root search more reliably for restoration. The heuristic isn't perfect but it's cheap to compute and relatively stable for common cases. I tried it in practice and it worked okay.
It's essentially `closestChildWithMeaningfulDisplayName : indexAmongRootsWithSameFirstPart`.
> Use a heuristic for locating roots

- OVERVIEW.md
- src/backend/renderer.js
- src/devtools/store.js
- src/devtools/views/Profiler/CommitTreeBuilder.js
When a large tree mounts or updates, in most cases strings are repetitive. For example, when interacting with a real complex app, I'm seeing how in every batch of `operations`, only ~10% of displayNames/keys are unique. The other ~90% are the same names that we encode multiple times. In the past, we've optimized encoding them to be cached. However, decoding is still lazy. It turns out that **decoding repetitive strings accounts for 40% of time spend in Store's `operations` handler**.
This fixes it with a string table. Individual events like `ADD` no longer contain the encoded strings. Instead, each batch of `operations` contains a list of unique strings in the beginning, and then further operations mention them by ID. I updated the `OVERVIEW` to explain the new format.
**Before:** 40ms in …
> Transfer strings in a string table

- src/__tests__/__snapshots__/storeOwners-test.js.snap
- src/__tests__/storeOwners-test.js
- src/__tests__/storeSerializer.js
- src/devtools/store.js
- src/devtools/views/Components/Element.js
- src/devtools/views/Components/Tree.js
- src/devtools/views/Components/TreeContext.js
> Owners list view should drill through intermediate components

- shells/browser/firefox/manifest.json
remove the `background` permissions as it's not used by Firefox, but `activeTab` is and we needed it.
fix #136
@bvaughn we may want to check the rest of this list for any others we might want specifically but from my testing this made it usable. 😄 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions
> fix: correct permissions for Firefox

- src/__tests__/storeSerializer.js
- src/devtools/store.js
I thought this might be a useful check for tests. This catches if we forget to delete something from a map in a store.
> Assert empty maps when there are no roots

- shells/browser/shared/src/backend.js
- shells/dev/src/backend.js
- src/__tests__/setupTests.js
- src/backend/agent.js
Let's make impossible states truly impossible, and fix Flow types, too.
All three usages of Agent called addBridge right after constructing it.
Agent has one field `_bridge` which is force-typed as not-null despite
there's a temporary zone between the constructor end and addBridge start
where `_bridge` is null.
> Remove Agent addBridge: there can only be one bridge, add in constructor

- .flowconfig
https://github.com/flowtype/flow-bin/issues/138#issuecomment-448416874
https://github.com/flowtype/flow-bin/issues/138#issuecomment-450367472
> This will stop flow from trying to consume too many virtual CPUs (which CircleCI doesn't actually provide), letting it run to completion without first running out of memory and killing its sub processes.
The log output in CircleCI was:
https://circleci.com/gh/bvaughn/react-devtools-experimental/201
```
#!/bin/bash -eo pipefail
yarn flow
yarn run v1.10.1
$ /home/circleci/repo/node_modules/.bin/flow
Launching Flow server for /home/circleci/repo
Spawned flow server (pid=259)
Logs will go to /tmp/flow/zShomezScirclecizSrepo.log
Monitor logs will go to /tmp/flow/zShomezScirclecizSrepo.monitor_log
Launching Flow server for /home/circleci/repo
Spawned …
```
> Fix Flow failure on CircleCI due to the number of workers

- src/backend/renderer.js
- src/backend/types.js
- src/devtools/ProfilingCache.js
- src/devtools/views/Profiler/CommitFlamegraph.js
- src/devtools/views/Profiler/CommitRanked.js
- src/devtools/views/Profiler/CommitTreeBuilder.js
- src/devtools/views/Profiler/FlamegraphChartBuilder.js
- src/devtools/views/Profiler/Interactions.js
- src/devtools/views/Profiler/InteractionsChartBuilder.js
- src/devtools/views/Profiler/RankedChartBuilder.js
- src/devtools/views/Profiler/SidebarInteractions.js
- src/devtools/views/Profiler/types.js
- src/devtools/views/Profiler/utils.js
Flow IDE shows the original type, not the file-scoped alias,
so it's confusing to see incompatible variables that have types
with the same name.
This started from [`src/devtools/ProfilingCache.js` where
`ProfilingSummary` was incompatible](https://github.com/bvaughn/react-devtools-experimental/pull/241), but I decided to make a bigger
change for consistency and to avoid similar mistakes in the future.
> Rename Profiler types to disambiguate which is Frontend and Backend

- .babelrc
- babel.config.js
- shells/browser/shared/webpack.backend.js
- shells/browser/shared/webpack.config.js
- shells/dev/webpack.config.js
I noticed our tests include regenerator transform which messes up the stack traces. As I was looking into why we have it, I realized we're not actually using `preset-env`. We didn't specify any targets so it behaves identically to `es2015`.
This changes our Babel config to actually use `preset-env`:
* For tests, we use the current Node environment.
* For the extension, we specify `chrome` and `firefox` versions from the respective manifest. I use an intersection to reduce the number of possible combinations.
Even that gives us a lot of ES6 syntax untranspiled. For example, `onBridgeOperations` no longer has an inner closure because it can use normal `let` / `const`.
And tests don't use regenerator now which will give us clearer failures.
> Start using @babel/preset-env

- src/__tests__/__snapshots__/store-test.js.snap
- src/__tests__/store-test.js
This adds more test coverage to the nested Suspense case. It's similar to what I usually manually test in the fixture. Unlike the stress test, it has nesting for Suspense.
Each case has a description of what you should see in the snapshot. I went through those and they look correct to me.
I didn't do the collapsed one because I wouldn't expect Suspense logic to leak into the store in a way that would also messed up collapsing. Also because it's a lot of expanding I'd have to do in the test and I'm feeling lazy. :P
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/177.
> Add test coverage for nested Suspense

- flow.js
- shells/browser/shared/src/backend.js
- shells/browser/shared/src/main.js
- shells/dev/src/backend.js
- shells/dev/src/devtools.js
- src/__tests__/setupTests.js
- src/bridge.js
- src/types.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/217
The error reproduces with any two React websites, e.g. `https://reactjs.org` and `https://nextjs.org`, by keeping the DevTools Components tab open and switching between these websites in the same browser tab.
There are several issues with the code that contribute to this:
1. `Bridge` leaves behind a dangling timer that fires `_flush` after the bridge has been abandoned ("shutdown").
2. `bridge.send('shutdown')` is asynchronous, so the event handlers do not get unsubscribed in time.
3. `port.onDisconnect` does not trigger on in-tab navigation like new URL or back/forward navigation.
4. State management design of the code that uses shared variables and callbacks makes it hard to handle race conditions originating from …
> Fix for 'Attempting to use a disconnected port object'

- package.json
- shells/dev/index.html
- shells/dev/src/devtools.js
- shells/dev/webpack.config.js
- yarn.lock
Three purposes:
* This ensures first load doesn't serve a stale build from previous development session. I always found it a bit confusing.
* We can live edit CSS now:
* Selfish goal: this will make it easier for me to test and dogfood the new React hot reloading implementation I'm experimenting with. (This PR doesn't enable it but it's useful to me locally.)
> Use WebpackDevServer for local testing

- src/backend/agent.js
- src/backend/renderer.js
- src/backend/types.js
- src/backend/views/Highlighter.js
- src/backend/views/Overlay.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/131
Uses the new function `findAllCurrentHostFibers`.
Removes dependency on React's `renderer.findHostInstanceByFiber` function
which used to highlight only the first DOM element of a Fragment.
Reworked `src/backend/views/Overlay` to support highlighting
more than one element rectangle annotated with one tooltip.
Fixed minor issues with the tooltip position calculation.
> Support highlighting of all DOM elements of Fragments, not just first

- shells/browser/shared/src/background.js
- shells/browser/shared/src/main.js
- shells/dev/src/backend.js
- src/__tests__/__snapshots__/profiler-test.js.snap
- src/__tests__/profiler-test.js
- src/backend/agent.js
- src/devtools/store.js
- src/devtools/views/Profiler/SidebarCommitInfo.js
Fix profiling screenshots data structure to map rootID to commitIndex
Propagate `rootID` throughout the code for `captureScreenshot`.
Rename private profiling maps of `store` to make relations more clear.
Fix missing cleanup for screenshots data in `set importedProfilingData` of `store`.
Clear profiling data for root when the root is unmounted
Fixes #232
> Clear profiling data for root when the root is unmounted. Fix profiling screenshots data structure to map rootID to commitIndex.

- package.json
- shells/browser/shared/build.js
- yarn.lock
Hello,
Firefox zip from demo website can't be imported and is corrupted (Same behavior than #34). I tried building the extension from scratch and got the same corrupted archive.
After some digging, it looks like the latest version of adm-zip introduced this issue for some users. 
Despite that switching to a prior version fixes the problem, this PR replaces adm-zip with ```node-archiver``` which is already in the dependency tree of the project.
> Replaced adm-zip with node-archiver

- .eslintignore
- src/__tests__/__snapshots__/profiling-test.js.snap
- src/__tests__/profiling-test.js
- src/__tests__/profilingCharts-test.js
- src/__tests__/setupTests.js
- src/__tests__/utils.js
- src/backend/agent.js
- src/backend/index.js
- src/backend/renderer.js
- src/backend/types.js
- src/devtools/ProfilingCache.js
- src/devtools/store.js
- src/devtools/views/Profiler/Interactions.js
- src/devtools/views/Profiler/ProfilingImportExportButtons.js
- src/devtools/views/Profiler/SidebarInteractions.js
- src/devtools/views/Profiler/types.js
- src/devtools/views/Profiler/utils.js
Cleanup profile export/import data types, add export/import test
Strengthened the I/O-boundary type conversion logic.
Fixed type inconsistencies uncovered by removing `any` and
by making explicit type annotations and transformations.
In particular, these were likely malformed when restored from a file:
- `commitDetails`
- `interactions`
- `initialTreeBaseDurations`
The mismatches were Map vs interleaved Array.
> Cleanup profile export/import data types, add basic tests

- .eslintrc
- shells/browser/chrome/manifest.json
- shells/browser/firefox/manifest.json
- shells/browser/shared/src/main.js
- src/__tests__/__snapshots__/profilerContext-test.js.snap
- src/__tests__/profilerContext-test.js
- src/bridge.js
- src/devtools/ProfilerStore.js
- src/devtools/views/Profiler/ClearProfilingDataButton.js
- src/devtools/views/Profiler/Profiler.js
- src/devtools/views/Profiler/ProfilerContext.js
- src/devtools/views/Profiler/ProfilingImportExportButtons.js
- src/devtools/views/TabBar.js
Resolves #235
Sometimes navigating from an SSR FB page to e.g. react-window.now.sh doesn't hand-off well though. Would be nice to know why that is, although I think that _also_ happens for the currently-released extension.
> [WIP] Don't erase profiler data on navigation

- shells/browser/shared/build.js
Hello,
Adding the extension in firefox shows a warning message related to WebExtension manifest file
Looks like Firefox WebExtension API [does not support ```version_name``` property yet](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version_name)
This PR removes version_name from Firefox manifest file
> Remove unsupported field from Firefox build

- src/__tests__/__snapshots__/profilingCache-test.js.snap
- src/__tests__/profilerContext-test.js
- src/__tests__/profilerStore-test.js
- src/__tests__/profilingCache-test.js
- src/__tests__/profilingCharts-test.js
- src/__tests__/profilingCommitTreeBuilder-test.js
- src/__tests__/storeComponentFilters-test.js
- src/backend/agent.js
- src/backend/renderer.js
- src/backend/types.js
- src/constants.js
- src/devtools/ProfilerStore.js
- src/devtools/store.js
- src/devtools/views/Profiler/Profiler.css
- src/devtools/views/Profiler/ReloadAndProfileButton.js
- src/devtools/views/Profiler/SidebarCommitInfo.css
- src/devtools/views/Profiler/SidebarSelectedFiberInfo.css
- src/devtools/views/Profiler/SidebarSelectedFiberInfo.js
- src/devtools/views/Profiler/types.js
- src/devtools/views/Profiler/utils.js
- src/devtools/views/Settings/Settings.js
I'm exploring how the Profiler UI might help answer the question: Why did <some component> re-render?
> Add profiling option to track why a component rendered

- src/devtools/views/root.css
Nitpicking.
I prefer it lighter because it leaves more contrast and subjectively makes it easier to read the names.
> Make children selection lighter

- src/backend/legacy/renderer.js
It only went one lever deep because we read the field wrong.
> Fix owner tree for legacy backend

- shells/dev/app/Hydration/index.js
- shells/dev/app/InspectableElements/Hydration.js
- shells/dev/app/InspectableElements/InspectableElements.js
- shells/dev/app/index.js
- src/__tests__/__snapshots__/inspectedElementContext-test.js.snap
- src/__tests__/inspectedElementContext-test.js
- src/__tests__/legacy/__snapshots__/inspectElement-test.js.snap
- src/__tests__/legacy/inspectElement-test.js
- src/backend/agent.js
- src/backend/legacy/renderer.js
- src/backend/renderer.js
- src/backend/types.js
- src/backend/utils.js
- src/bridge.js
- src/devtools/views/Components/ExpandCollapseToggle.js
- src/devtools/views/Components/HooksTree.js
- src/devtools/views/Components/InspectedElementContext.js
- src/devtools/views/Components/InspectedElementTree.js
- src/devtools/views/Components/KeyValue.css
- src/devtools/views/Components/KeyValue.js
- src/devtools/views/Components/SelectedElement.js
- src/devtools/views/Components/types.js
- src/devtools/views/utils.js
- src/hydration.js
- src/utils.js
Resolves #195 (and generally improves performances for props-heavy components)
Prior to this change, inspecting a component serialized the first 5 nested levels of props/state/context data. This was okay for most cases- but in some extreme cases (objets with **a lot** of nested properties) this could cause a performance bottleneck. After this PR, we truncate nested objects much more aggressively. Now we only send their data over the bridge on-demand (similar to how v3 DevTools worked).
Internally, this technique is referred to as "dehydrating" and "hydrating" the values. Past a certain depth, nested values get "dehydrated" such that only metadata is sent across the bridge. The UI then requests these values be "hydrated" on-demand (when the user expands them) to fill in the missing data. …
> Lazily send props/state/hooks across the bridge

- src/devtools/views/Profiler/SidebarSelectedFiberInfo.css
- src/devtools/views/Profiler/SidebarSelectedFiberInfo.js
Fixes #324.  This PR ensures that short sections of content in the profiler sidebar are always shown, even when there are a large number of renders shown in the sidebar. Without this PR, if there are many renders then the CSS `overflow-y: auto` would hide content like "why did this render?" until you scrolled down to see it, which is undiscoverable because there's no scrollbar or other indicator letting you know there's hidden content.
This PR divides sidebar content into "short" content (always show all of it without scrolling) and "maybe long" content (scrolling is OK). The "short" content gets `overflow-y: visible` while the "maybe long" content gets `overflow-y: auto`.
I tested locally in latest Chrome and latest Firefox and PR works as expected. 
For verification steps, see #324.
> fix: ensure when-rendered content is never hidden

- src/backend/renderer.js
This is for https://github.com/facebook/react/pull/15927 (if it lands). It updates the `displayName` location on event components.
> [Flare] Update event component displayName

- shells/browser/shared/src/renderer.js
The devtools use a different way to attach the renderer with the "reload-and-profile" functionality. Before this PR it was setting it via a non-configurable object property making it impossible to set to something else. This breaks compatibility with third party clients like Preact.
Instead of going the `Object.defineProperty` way, we can just assign the property directly. Clicked a bit around in a sample CRA-App and both the standard devtools features as well as the reload-and-profile continue to work for me :tada:
> Fix reload-and-profile attach not configurable

- src/devtools/views/Components/EditableValue.js
This is to fix #346.
This makes `parseFloat` delay until pressing `enter`.
> fix to input a negative number value to props

- src/devtools/views/Components/TreeContext.js
This pr closes #301 
The strategy used here was: Get the first index where elementID is larger than the selected element and reorder the search results for these elements so that the range with the largest is at the beginning of the matrix and the range with the smallest in the end.
> Feature: tweak search behaviour

- shells/dev/app/Iframe/index.js
- shells/dev/app/index.js
- src/backend/agent.js
- src/backend/views/Highlighter/index.js
This change adds support for element inspecting within `<iframe/>`s.
The iframes are kept in a Set so that we only append listeners once and clean them up properly. I’ve run a few tests and it seems to behave as expected.
Here’s a screencapture: http://cl.ly/358a8f22715d/iframe-demo.mov
The fixture includes a cross-origin iframe to make sure we do not error in this case.
I’ve run through the following scenarios locally:
- Nexted iframes
- Iframe is removed while we’re inspecting
- Chrome and Firefox
Let me know if/where I should add tests. 🙂
> Allow Inspecting Elements Within Iframes

- src/backend/ReactDebugHooks.js
- src/backend/types.js
We've renamed the `useListener` hook to `useResponder` and it now returns a React Responder Listener object.
> [Flare] useListener -> useResponder

- packages/react-devtools-core/src/backend.js
- src/backend/agent.js
- src/backend/legacy/renderer.js
- src/backend/renderer.js
- src/backend/types.js
- src/bridge.js
- src/devtools/views/Components/InspectedElementContext.js
Closes #357
This change enables a few things:
* Removes a redundant `Bridge` message.
* Enables `$r` to include hooks info for function components.
* Ensures `$r` is periodically updated if the selected element is re-rendered.
One thing to note is that the `hooks` value exposed is the internal data structure created by [`react-debug-hooks`](https://github.com/bvaughn/react-devtools-experimental/blob/master/src/backend/ReactDebugHooks.js) so it isn't necessarily as parsable or useful as the `props` or `state` objects. Still seems better than nothing though?
> Refactor inspect/select logic so that $r contains hooks data

- src/__tests__/__snapshots__/treeContext-test.js.snap
- src/__tests__/treeContext-test.js
- src/devtools/views/Components/TreeContext.js
closes #299
Enables the user to use the component search capability against HOC display names.
> feat: match HOC display names during search
