src/devtools/views/Elements/KeyValue.css
Fixes #19 - Break the text into next line for long props
=> Break the text into next line for long props

shells/browser/shared/src/main.js
for some reason, this work on my mac, but when I tried to build on a linux machine it broke.
=> Fix casing on store import

shells/dev/app/SuspenseTree/index.js, shells/dev/app/index.js, src/backend/renderer.js, src/constants.js, src/devtools/store.js, src/devtools/views/Profiler/CommitTreeBuilder.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/68.
You can verify with the fixture. (It would be nice to expand it or make a fuzzer in the future.)
I don't know if the fix is 100% correct, but it should be more correct than master.
=> Fix Suspense fragment edge cases

src/backend/agent.js, src/backend/views/Overlay.js
This shows the owner name in DOM highlighter when the owner information is available.
I think this makes inspecting unfamiliar hierarchies a bit easier.
=> Show owner in DOM highilght overlay

src/backend/renderer.js
This isn't used anywhere. I added it at some point but then went for another approach and forgot to delete.
=> Remove dead code

src/devtools/views/Button.js, src/devtools/views/Components/HooksTree.js, src/devtools/views/Components/InspectedElementTree.js, src/devtools/views/Profiler/SnapshotSelector.js
=> Add missing Button titles

shells/browser/shared/src/main.js
Fixes https://github.com/bvaughn/react-devtools-experimental/pull/103#discussion_r273619654.
=> Send the bridge sync event lazily

src/devtools/views/Components/Element.css, src/devtools/views/Components/Element.js, src/devtools/views/Components/Tree.js, src/devtools/views/Settings/SettingsContext.js, src/devtools/views/root.css
fixes #106 
not super happy with the colors I've chosen, but here's what they look like
=> Add inactive color on components when window isn't focused

src/bridge.js
=> Improve bridge batching logic

src/devtools/views/Components/Tree.js, src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/121#issuecomment-481773140.
=> Left and right arrows only traverse parents

src/devtools/views/Components/Tree.js
Needs https://github.com/bvaughn/react-window/pull/209 to work. See demo gif there.
Would need a package.json bump too.
=> Use smart scrolling

.gitignore, package.json, shells/browser/chrome/build.js, shells/browser/chrome/manifest.json, shells/browser/chrome/now.json, shells/browser/chrome/updates.xml, shells/browser/shared/build.js, shells/browser/shared/deploy.chrome.html, shells/browser/shared/deploy.firefox.html, shells/browser/shared/deploy.js, yarn.lock
Make use of the [`update_url`](https://developers.chrome.com/apps/autoupdate) mechanism to push  updates to beta testers.
=> Auto-update Chrome extension

package.json, src/devtools/views/Components/Tree.js, src/devtools/views/Profiler/Profiler.js, src/devtools/views/Profiler/ToggleCommitFilterModalButton.js, yarn.lock
Updates and fixes a few violations (useless `useCallback`)
=> Bump React Hooks plugin

src/devtools/views/Components/Tree.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/153.
Instead of a ref that's being read in a render phase, I re-modeled this remembered "minimum width" as state. This state is derived. It gets reset when we enter the owner view — or if it's resized. If this state is reset, we do a render with `100%` and then fill in the state again in the effect.
=> Adjust highlighting on window resize

src/utils.js
We spend a significant amount of time on encoding strings for large trees. However, those encoded strings tend to be the same ones (for example, component names are highly repetitive). So we do both unnecessary encoding and allocation of typed arrays, which in turn increase GC pressure.
This adds an LRU cache for their encoded versions. I picked 1000 based on internal testing on FB. It's large enough to keep the cache nice and warm, but reasonably limited. These strings normally wouldn't be large anyway.
This cuts down the time spent in this function alone from ~20% of a large update to ~0%.
=> Use LRU for encoded strings

package.json, shells/dev/webpack.config.js
=> Add production mode to dev shell

src/backend/renderer.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/157.
We used to copy and recreate the typed array on every operation. This is very costly.
This changes our queue to be a mutable array of integers — and delays the movement into typed array until the transfer. (Note that in practice we don't get to use it in Chrome, and have to fall back to JSON anyway. But I didn't see significant overhead to creating a final typed array so it seems like we can keep that constraint and enjoy even faster transfer on FF for now.)
=> Don't materialize typed array until the transfer

src/__tests__/__snapshots__/store-test.js.snap, src/__tests__/setupTests.js, src/__tests__/store-test.js, src/__tests__/storeStress-test.js, src/devtools/store.js, src/devtools/views/Components/TreeContext.js, src/devtools/views/Settings/Settings.css, src/devtools/views/Settings/Settings.js
=> Configurable tree default collapsed/expanded behavior

src/__tests__/__snapshots__/store-test.js.snap, src/__tests__/store-test.js, src/devtools/store.js
=> Fixed a Suspense toggling bug that incorrectly impacted tree weight

src/devtools/views/Components/TreeContext.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/187.
We already set the boolean flag on specific user actions (navigate to prev/next).
=> Don't select search result unless user does something

src/backend/renderer.js
=> Don't reorder a single child

src/backend/renderer.js
The intermediate `nextOperation` array was necessary when we conditionally appended its contents to either start or end of the queue. But we've removed the need for that. It's always end of the queue now. So we might as well write to the queue directly. This avoids unnecessary copying and I think reads a bit easier.
=> Push operations directly to the array

src/devtools/store.js
I'm seeing ~15% improvement for additions in ~20% improvement for deletions on huge trees with this change. Probably because we copy less and because we don't churn the GC as much.
=> Improve performance by mutating the children array

.flowconfig, src/backend/renderer.js, src/backend/types.js
Fixes https://github.com/bvaughn/react-devtools-experimental/issues/165
CC @gaearon
=> Add Flow types for Fiber

src/devtools/views/Profiler/FlamegraphChartBuilder.js
=> Right-align flame graph children

src/devtools/views/Profiler/CommitFlamegraph.js
=> Fix undefined chart node when switching commits in profiler
